/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArcCalculator: typeof import('./src/components/minecraft/arcCalculator.vue')['default']
    Day: typeof import('./src/components/days/day.vue')['default']
    MapDisplay: typeof import('./src/components/map/mapDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Showcase: typeof import('./src/components/showcase.vue')['default']
  }
}
